version: "3.9"
services:
  api:
    image: tiangolo/uvicorn-gunicorn-fastapi:3.8
    command: /start-reload.sh
    environment:
      - MAX_WORKERS=1
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
