version: "3.9"
services:
  # celery:
  #   hostname: celery
  #   image: background-tasks-celery:latest
  #   build:
  #     context: .
  #     target: celery
  #   volumes:
  #     - ./src:/demo
  #   working_dir: /demo
  #   env_file: .env
  #   depends_on:
  #     - redis
  #     - rabbitmq

  dramatiq:
    hostname: dramatiq
    image: background-tasks-dramatiq:latest
    build:
      context: .
      target: dramatiq
    volumes:
      - ./src:/demo
    working_dir: /demo
    env_file: .env
    depends_on:
      - redis
      # - rabbitmq

  redis:
    hostname: redis
    image: redis:6

  # rabbitmq:
  #   hostname: rabbitmq:3
  #   image: rabbitmq

  # flower:
  #   hostname: flower
  #   image: mher/flower
  #   depends_on:
  #     - celery
